# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realm_study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for realm_study
  pod 'RealmSwift'

  target 'realm_studyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'realm_studyUITests' do
    # Pods for testing
  end

end
